DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS crypto;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS crypto (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  crypto_name TEXT NOT NULL,
  crypto_symbol TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
