[project]
name = "application"
version = "1.0.0"
description = "Application to track cryptocurrencies and receive live notifications to help automate investment decisions."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"